### ISSUE TITLE
文件上传问题！

### ISSUE THREAD

**Issue by mfkwvf** [chekun/DiliCMS#29]
用的系统自带的swfloader   8M 以下的文件可以上传，8M以上的文件上传不了。我传的是MOV文件！
服务器配置没问题，找了半天没解决，求大大帮忙。

如果有需要，我可以发SSH和FTP给大大看。

**Comment by chekun** [comment]
8M 如果服务器配置好了的话，绝对不会有问题。

请给出web服务器容器配置，以及php.ini配置

**Comment by mfkwvf** [comment]
![image](https://f.cloud.github.com/assets/4373899/1000467/127ec820-0a4c-11e3-8a40-02b919f3e353.png)

php.ini

[PHP]

max_execution_time = 3600     ; Maximum execution time of each script, in seconds
max_input_time = 60 ; Maximum amount of time each script may spend parsing request data
;max_input_nesting_level = 64 ; Maximum input variable nesting level
memory_limit = 500M      ; Maximum amount of memory a script may consume (128MB)

; Maximum size of POST data that PHP will accept.
post_max_size = 500M

; Maximum allowed size for uploaded files.
upload_max_filesize = 200M

; Maximum number of files that can be uploaded via a single request
max_file_uploads = 20

;;;;;;;;;;;;;;;;;;
; Fopen wrappers ;
;;;;;;;;;;;;;;;;;;

; Whether to allow the treatment of URLs (like http:// or ftp://) as files.
allow_url_fopen = On

; Whether to allow include/require to open URLs (like http:// or ftp://) as files.
allow_url_include = Off

; Define the anonymous ftp password (your email address)
;from="john@doe.com"

; Define the User-Agent string
; user_agent="PHP"

; Default timeout for socket based streams (seconds)
default_socket_timeout = 60

; If your scripts have to deal with files from Macintosh systems,
; or you are running on a Mac and need to deal with files from
; unix or win32 systems, setting this flag will cause PHP to
; automatically detect the EOL character in those files so that
; fgets() and file() will work regardless of the source of the file.
; auto_detect_line_endings = Off

**Comment by chekun** [comment]
server是apache还是nginx？

**Comment by mfkwvf** [comment]
apache

**Comment by mfkwvf** [comment]
找到问题了，谢谢老大！问题原因是我装的WDCP管理平台，他默认用的是nginx+apache，我单独使用apache成功解决了问题。感谢大大的耐心指导！！

**Comment by chekun** [comment]
不客气，还是服务器配置问题。
