### ISSUE TITLE
下拉菜单(数据模型)(INT)无法及时更新

### ISSUE THREAD

**Issue by yuguo** [chekun/DiliCMS#3]
新建了一个分类模型cat，一个内容模型item，然后item中有一个字段用了下拉菜单(数据模型)(INT)，选定cat|slug
修改分类管理中的内容以后，内容管理的的item下拉没有及时出现修改后的分类，需要手动更新下分类模型管理。

**Comment by chekun** [comment]
目前是这样子的，当初的想法是分类模型更新频率不频繁，所以采用了手动更新的方式。
