### ISSUE TITLE
安装程序在windows apache php 环境下无法正常运行

### ISSUE THREAD

**Issue by csbde** [chekun/DiliCMS#45]
# 点击进入 http://www.dilicms.dev/install/public/ 后出现404错误
- dilicms 2.3.1
- window
- apache
- php 5.3

**Comment by chekun** [comment]
从URL上看，你是去掉了index.php，但是你的URL重写规则设置的不对，导致出现了404。

**Comment by csbde** [comment]
没有在配置里去掉index.php
不知道是不是我的apache配置的问题，我换nginx+php就可以正常使用了。 谢谢你的回复
