### ISSUE TITLE
database.php配置归一化

### ISSUE THREAD

**Issue by chekun** [chekun/DiliCMS#48]
- [x] 完成代码
- [x] 完成windows平台测试
- [x] 完成Linux/Unix平台测试

**Comment by fuxu** [comment]
我看到next-generation已经准备用laravel写了, ci这边还准备做功能增强?

**Comment by chekun** [comment]
@dickfu 现阶段仍然会继续使用CI开发，先维持一下这个版本，也会用CI重构一下。

**Comment by chekun** [comment]
Done via #49
