### ISSUE TITLE
Stored-XSS Vulnerability Found in System setting -> site setting

### ISSUE THREAD

**Issue by RoodyChan** [chekun/DiliCMS#57]
# Steps to Reproduce

**1、Login the backstage**
http://127.0.0.1/DiliCMS-develop-3.x/admin/index.php

**2、Go to System setting->site setting**
![dilicms-xss0](https://user-images.githubusercontent.com/29420758/39287303-9c44cf0a-4912-11e8-9f40-d028cbc5903b.jpg)

**3、add the following payload to the fourth textbox**
1"</input><script>alert(123)</script>
![dilicms-xss6](https://user-images.githubusercontent.com/29420758/39287273-738321c0-4912-11e8-8798-1c395a8b5832.jpg)

**4、Save and see the announcement we just posted**
![dilicms-xss5](https://user-images.githubusercontent.com/29420758/39287316-aa00a772-4912-11e8-809e-b6e4e70940ec.jpg)

![dilicms-xss7](https://user-images.githubusercontent.com/29420758/39287275-77c95100-4912-11e8-9290-6b11b2cccec5.jpg)

And then Stored-XSS triggered ...

**Comment by chekun** [comment]
Yes,  Thank you. But `DiliCMS` is not a  software for production literally.
this vulnerability can be easily fixed by setting `global_xss_filtering` to `true` in config file https://github.com/chekun/DiliCMS/blob/v2.4.0/application/config/config.php#L282
